name: Lint and validate OpenAPI specs
on:
  - push
  - pull_request
jobs:
  lint:
    name: Lint OpenAPI definition
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v2
      - name: Run OpenAPI Lint Action
        uses: nwestfall/openapi-action@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: openapi/workflow_execution_service.openapi.yaml
  diff:
    name: Show OpenAPI differences relative to target branch
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: head
      - name: Check out base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: base
      - name: Run OpenAPI Diff Action
        uses: mvegter/openapi-diff-action@v0.23.5
        with:
          head-spec: head/openapi/workflow_execution_service.openapi.yaml
          base-spec: base/openapi/workflow_execution_service.openapi.yaml

  validate:
    name: Validate OpenAPI definition
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v2
      - name: Run OpenAPI Validate Action
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: openapi/workflow_execution_service.openapi.yaml


name: docs-build-publish
on:
  push:
    branches:
      - master
      - develop
      - "feature/issue-*"
      - "fix/issue-*"
      - "support/issue-*"
  pull_request:
    branches:
      - master
      - develop
      - "feature/issue-*"
      - "fix/issue-*"
      - "support/issue-*"
jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Pull 🐳
        run: |
          docker pull ga4gh/gh-openapi-docs:0.2.3-rc1
      - name: Build Docs 🔧
        run: |
          docker run --name docs-builder --rm -v `pwd`:/docs ga4gh/gh-openapi-docs:0.2.3-rc1
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: publish
